#!bin/bash
set -euo pipefail
IFS=$'\n\t'
trap ctrl_c 2

R='\033[1;31m'
azul='\e[1;34m'
G='\033[1;32m'
Y='\033[1;33m'
B='\033[1;34m'
M='\033[1;35m'
C='\033[1;36m'
cyan='\e[1;36m'
W='\033[0m'
N='\e[1;30m'


clear
echo -e "
████████╗ ██████╗  ██████╗ ██╗     ██╗     ███████╗ ★ f3r.. . ★
╚══██╔══╝██╔═══██╗██╔═══██╗██║     ██║     ██╔════╝ ★ dark    ★
   ██║   ██║   ██║██║   ██║██║     ██║     ███████╗ ★ cebra.. ★
   ██║   ██║   ██║██║   ██║██║     ██║     ╚════██║ ★ shadow  ★
   ██║   ╚██████╔╝╚██████╔╝███████╗███████╗███████║ ★ Joker.. ★
   ╚═╝    ╚═════╝  ╚═════╝ ╚══════╝╚══════╝╚══════╝ ★ Arctic. ★
 ★★-★-★-★-★-★-★-★-S.H.A.R.K.C.O.D.E-★-★-★-★-★-★-★-★★" | lolcat
echo
	printf "$Y"
        echo -e "$C  [1] $Y Actualizar Paquetes"
        echo -e "$C  [2] $Y Herramientas hacking"
        echo -e "$C  [3] $R Salir:(.. $B"
echo
echo

        while read -p "Que opcion quieres?  >> " SIGN && [ -z $SIGN ]; do
		printf "$R
		Porfavor escribe un numero valido puto
		\n $W"
	done


if [ $SIGN -eq '1' ]; then

clear
echo -e "$N
████████╗ ██████╗  ██████╗$G ██╗     ██╗     ███████╗ ★ f3r.. . ★ $N
╚══██╔══╝██╔═══██╗██╔═══██╗$G██║     ██║     ██╔════╝ ★ dark    ★ $N
   ██║   ██║   ██║██║   ██║$G██║     ██║     ███████╗ ★ cebra.. ★ $N
   ██║   ██║   ██║██║   ██║$G██║     ██║     ╚════██║ ★ shadow  ★ $N
   ██║   ╚██████╔╝╚██████╔╝$G███████╗███████╗███████║ ★ jocker. ★$N
   ╚═╝    ╚═════╝  ╚═════╝$G ╚══════╝╚══════╝╚══════╝ ★ Artic.. ★  "$W
echo -e    "$G ★★-★-★-★-★-★-★-★-S.H.A.R.K.C.O.D.E-★-★-★-★-★-★-★-★★" 
echo

echo -e "$Y Solo actualizare o instalare los recursos basicos"
echo
echo
echo -e "$G[chicharron] Instalando..."
apt-get update -y > /dev/null 2>&1
apt-get upgrade -y > /dev/null 2>&1
sleep 3
printf "$G \n \t Listoo paquetes actualizados !!"
echo
printf "$C \n \t presiona en $G enter $C para continuar"
echo
read enter
echo
source $HOME/HerraShark/Tools1

elif [ $SIGN -eq '2' ]; then

clear
echo -e "$N
████████╗ ██████╗  ██████╗$G ██╗     ██╗     ███████╗ ★ f3r.. . ★ $N
╚══██╔══╝██╔═══██╗██╔═══██╗$G██║     ██║     ██╔════╝ ★ dark    ★ $N
   ██║   ██║   ██║██║   ██║$G██║     ██║     ███████╗ ★ cebra.. ★ $N
   ██║   ██║   ██║██║   ██║$G██║     ██║     ╚════██║ ★ shadow  ★ $N
   ██║   ╚██████╔╝╚██████╔╝$G███████╗███████╗███████║ ★ jocker. ★$N
   ╚═╝    ╚═════╝  ╚═════╝$G ╚══════╝╚══════╝╚══════╝ ★ Artic.. ★  "$W
echo -e " $G★★-★-★-★-★-★-★-★-S.H.A.R.K.C.O.D.E-★-★-★-★-★-★-★-★★"
echo

printf "$C [chicharron]$G Extrayendo programas.. $Y \n"
echo
echo
echo -e "$G Instalando phoneinfoga"
git clone https://github.com/sundowndev/phoneinfoga > /dev/null 2>&1
echo
echo
printf "$C Listoo Phoneinfoga instalado !!"
echo
echo
echo -e "$G Instalando sherlock"
git clone https://github.com/sherlock-project/sherlock > /dev/null 2>&1
sleep 0.5
echo
echo
printf "$C Listoo sherlock instalado !!"
echo
echo
echo -e "$G Instalando sara malware"
git clone https://github.com/termuxhackers-id/SARA > /dev/null 2>&1
sleep 0.5
echo
echo
printf "$C Listo Sara instalado !!"
echo
echo
echo -e "$G Instalando Foto sploit"
git clone https://github.com/Cesar-Hack-Gray/FotoSploit > /dev/null 2>&1
sleep 05
echo
echo
printf "$C Listo Fotosploit instalado !!"
sleep 0.5
echo
echo
printf "$C \n \t Presiona en $G enter $C para continuar"
echo
read enter
source $HOME/HerraShark/Tools1

elif [ $SIGN -eq '3' ]; then
clear
echo -e "
 █████╗ ██████╗ ██╗ ██████╗ ███████╗
██╔══██╗██╔══██╗██║██╔═══██╗██╔════╝
███████║██║  ██║██║██║   ██║███████╗
██╔══██║██║  ██║██║██║   ██║╚════██║
██║  ██║██████╔╝██║╚██████╔╝███████║
╚═╝  ╚═╝╚═════╝ ╚═╝ ╚═════╝ ╚══════╝
" | lolcat
echo ""
echo -e "$R gracias por ocupar la herramienta Pronto mas opciones"
echo ""
echo -e "$G Adios..!!"

else


	       bash $PREFIX/bin/bash

fi
